server.port: 8181
spring:
  application.name: book-service
  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false
    username: root
    password: rootroot
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
